name: perkeep_uploader
description: A flutter app that syncs photos to perkeep
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  photo_manager: ^2.1.4
  settings_ui: ^2.0.2
  shared_preferences: ^2.0.15
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
